Add elasticseearch
cohere-ai/cohere-toolkit pull request #115
Opened 2024-05-08 08:24 UTC by Justicea83

Thank you for contributing to the Cohere Toolkit!

- [ ] **PR title**: "Add search to ELK cluster"
  - Add changes to add search from ELK stack
  - Example: "deployment: Cohere Platform"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** Add Elasticsearch retriever
    - **Dependencies:** `elasticsearch`

<img width="808" alt="Screenshot 2024-05-03 at 19 02 05" src="https://github.com/cohere-ai/cohere-toolkit/assets/26106822/9192a3c9-2eaa-4908-87a6-c98b3ebbea09">

<img width="1100" alt="Screenshot 2024-05-03 at 19 17 45" src="https://github.com/cohere-ai/cohere-toolkit/assets/26106822/d48933bf-6d4e-4c0e-8bd0-ce6794b45026">

2024-05-08 08:58 UTC, Justicea83 commented
@tianjing-li tagging you because this is a new version of the previously closed PR [here](https://github.com/cohere-ai/cohere-toolkit/pull/100)

2024-05-08 19:17 UTC, tianjing-li commented on src/community/config/tools.py
> +        error_message="The host and index env variables are required.",
Just clarify the exact variables eg `ELASTICSEARCH_HOST` and `ELASTICSEARCH_INDEX` here

2024-05-08 19:19 UTC, tianjing-li requested changes
Minor change then good to go, you'll also need to sign all your previous commits.

You can setup a GPG key (see the readme) and then run the following:


`git reset $(git merge-base main $(git branch --show-current))`
^it undos all your commits and adds it to you local changes
then
`git commit -S -m "your message" `
git push --force

2024-05-09 16:55 UTC, Justicea83 commented
Bumping for reviews

2024-05-13 20:37 UTC, lusmoura commented on src/interfaces/coral_web/src/hooks/startModes.tsx
> +import {DEFAULT_CHAT_TOOL, DEFAULT_ELASTIC_SEARCH_TOOL} from '@/cohere-client';
Would you mind removing the FE changes? Since the community features are not required to run the toolkit, this could lead to errors or confusing UX.

2024-06-18 16:07 UTC, tianjing-li commented
@Justicea83 Would you be able to update this PR?

2024-07-02 20:46 UTC, tianjing-li commented
@Justicea83 closing this PR for now, since it is no longer up to date

2024-07-02 20:46 UTC, closed without merging