coral_web: Add is_available check to tools
cohere-ai/cohere-toolkit pull request #82
Opened 2024-04-30 21:10 UTC by misspia-cohere

**Description**
- filter out tools that have a false `is_available` value

2024-04-30 21:21 UTC, wujessica commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
there's also a part of this task to read and display the `error_message` field!

2024-04-30 21:26 UTC, misspia-cohere commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
oh I see-- like a tooltip next to the tool maybe?

2024-04-30 21:32 UTC, misspia-cohere commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
suggesting tooltip instead of rendering directly in the list of tools as some messages can be lengthy

ie.
![Screenshot 2024-04-30 at 17 31 47](https://github.com/cohere-ai/cohere-toolkit/assets/140425731/b39fd99e-1131-4077-8de8-205d84202050)

2024-04-30 21:38 UTC, wujessica approved these changes

2024-04-30 21:38 UTC, wujessica commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
wait do these all usually have errors LOL but they still work? 🤣 confused haha

2024-04-30 21:38 UTC, wujessica commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
> +                <div key={name} className="flex gap-x-1">
let's centre the button!
```suggestion
                <div key={name} className="flex items-center gap-x-1">
```

2024-04-30 21:38 UTC, wujessica commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
>                      onChange={async (e) => {
not part of this but I don't think we need this `async`
```suggestion
                    onChange={(e) => {
```

2024-04-30 21:43 UTC, misspia-cohere commented on src/interfaces/coral_web/src/components/Configuration/Tools.tsx
seems like it ¯\_(ツ)_/¯

2024-04-30 21:53 UTC, wujessica approved these changes

2024-04-30 23:49 UTC, tianjing-li commented
I think we want to show the ones that have `is_available=False`, but perhaps just make them red (or some other indicator that they're not selectable) and to show their error_message. And the tooltip message should use `description` if it's available, but use `error_message` if its not available. Lmk if that makes sense

2024-04-30 23:49 UTC, tianjing-li requested changes
Added some feedback

2024-05-01 14:17 UTC, wujessica approved these changes

2024-05-01 15:27 UTC, tianjing-li approved these changes
Approved - ty for changing

2024-05-01 15:29 UTC, merged